import base64

s = "wATjd/JrLBEEAAEABeHvbQUoIMWQwMGZmZmZVAACAP1pAMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDQwMDA0MDAwNGJAMDAwMDAwMDA2YTYyNWYwNjYzNmI4YmI2YWM3Yjk2MGE4ZDAzNzA1ZDFhY2UwOGIxYTE5ZGEzZmRjYzk5ZGRiZGpAMDAwMDAwMDA0ZWJhZGI1NWVlOTA5NmM5YTJmODg4MGUwOWRhNTljMGQ2OGIxYzIyOGRhODhlNDg4NDRhMTQ4NQ=="
k = base64.b64decode(s)
print "".join("{:02x}".format(ord(c)) for c in k)